/**
 * inference_engine.c
 * Bare-metal INT8 inference engine — pure integer arithmetic
 * No stdlib math, no malloc, no FPU required.
 *
 * Key design decisions for 16KB SRAM constraint:
 *   - All buffers statically allocated
 *   - Layers computed sequentially, output overwrites input buffer
 *   - Multiplier/shift requantization (avoids float division)
 *   - Feature vector size capped at MAX_FEATURES
 */

#include "inference_engine.h"
#include <string.h>

/* ── Static buffers (no heap) ───────────────────────────────────────── */
#define MAX_FEATURES  256    /* max neurons in any hidden layer */

static int8_t s_buf_a[MAX_FEATURES];  /* ping-pong buffers   */
static int8_t s_buf_b[MAX_FEATURES];  /* for layer outputs   */

/* ── Quantized model weights (dense layers only) ────────────────────── 
 *
 * IMPORTANT: These arrays are populated by the Python notebook output.
 * After running CrackDetection_Training.ipynb, replace the placeholder
 * values below with the actual exported weights from:
 *   python_training/export_weights.py   (run after the notebook)
 *
 * Architecture exported: MobileNetV2 features → GAP → Dense(64,relu) → Dense(1,sigmoid)
 * 
 * For simulation testing before training, the placeholder weights below
 * implement a simple threshold classifier that demonstrates the pipeline.
 * ───────────────────────────────────────────────────────────────────── */

/* Layer 1: Dense 64 → hidden
 * Shape: [64 out, 64 in] = 4096 weights
 * REPLACE with actual exported weights after training
 */
#define L1_IN   64
#define L1_OUT  64
#define L2_IN   64
#define L2_OUT  1

/* Placeholder: diagonal-ish weights for pipeline testing */
static const int8_t s_w1[L1_OUT * L1_IN] = {
    /* 4096 INT8 values — replace with notebook output */
    #include "weights/layer1_weights.inc"  /* generated by notebook */
};

static const int32_t s_b1[L1_OUT] = {
    /* 64 INT32 biases — replace with notebook output */
    #include "weights/layer1_biases.inc"
};

/* Layer 2: Dense 64 → 1 (sigmoid output) */
static const int8_t s_w2[L2_OUT * L2_IN] = {
    #include "weights/layer2_weights.inc"
};

static const int32_t s_b2[L2_OUT] = {
    #include "weights/layer2_biases.inc"
};

/* Requantization parameters (generated by notebook) */
#define L1_MULTIPLIER  1073741824   /* Q2.30 */
#define L1_SHIFT       0
#define L1_OUT_ZERO    0

#define L2_MULTIPLIER  1073741824
#define L2_SHIFT       0
#define L2_OUT_ZERO    0

/* ── Helpers ─────────────────────────────────────────────────────────── */

/* Saturate int32 to int8 range */
static inline int8_t saturate_int8(int32_t x) {
    if (x >  127) return  127;
    if (x < -128) return -128;
    return (int8_t)x;
}

/* Multiply-and-right-shift (Q2.30 requantization) */
static inline int32_t multiply_by_quantized_multiplier(
        int32_t x, int32_t multiplier, int shift) {
    /* Arithmetic right shift with rounding */
    int64_t result = (int64_t)x * multiplier;
    result += (int64_t)1 << (30 - 1 - shift);  /* round-to-nearest */
    return (int32_t)(result >> (30 - shift));
}

/* ── Activation functions ────────────────────────────────────────────── */

int8_t relu_int8(int32_t x, int32_t zero_point) {
    return saturate_int8(x < zero_point ? zero_point : x);
}

/**
 * Piecewise-linear sigmoid approximation.
 * Divides [-128, 127] into 5 segments with linear interpolation.
 * Output is in INT8 space with zero_point=0.
 *
 *  x < -64  →  output ≈ -127  (sigmoid ≈ 0 → INT8 -127)
 * -64 to -16 → linear segment
 * -16 to +16 → steep linear (most of the transition)
 * +16 to +64 → linear segment
 *  x > +64  →  output ≈ +127  (sigmoid ≈ 1 → INT8 +127)
 */
int8_t sigmoid_int8_approx(int32_t x) {
    if (x <= -64) return -127;
    if (x >=  64) return  127;
    if (x < -16) {
        /* slope ≈ 0.88 in this region */
        return saturate_int8(-127 + (int32_t)((x + 64) * 225 >> 7));
    }
    if (x > 16) {
        return saturate_int8(127 - (int32_t)((64 - x) * 225 >> 7));
    }
    /* Central steep region: slope ≈ 3.96 */
    return saturate_int8(x * 127 / 16);
}

/* ── Dense layer ─────────────────────────────────────────────────────── */

void dense_layer_int8(
    const int8_t  *input,
    const int8_t  *weights,
    const int32_t *biases,
    int8_t        *output,
    uint16_t       in_feat,
    uint16_t       out_feat,
    int32_t        multiplier,
    int32_t        shift,
    int32_t        out_zero,
    uint8_t        activation)
{
    for (uint16_t o = 0; o < out_feat; o++) {
        /* 32-bit accumulator — no overflow for int8 * int8 * 256 inputs */
        int32_t acc = biases[o];

        const int8_t *row = weights + (int32_t)o * in_feat;
        for (uint16_t i = 0; i < in_feat; i++) {
            acc += (int32_t)row[i] * (int32_t)input[i];
        }

        /* Requantize to INT8 output range */
        int32_t scaled = multiply_by_quantized_multiplier(acc, multiplier, shift);
        scaled += out_zero;

        /* Apply activation */
        switch (activation) {
            case ACT_RELU:
                output[o] = relu_int8(scaled, out_zero);
                break;
            case ACT_SIGMOID:
                output[o] = sigmoid_int8_approx(scaled);
                break;
            default:
                output[o] = saturate_int8(scaled);
                break;
        }
    }
}

/* ── Global Average Pooling (spatial → feature vector) ──────────────── */

/**
 * global_avg_pool_int8()
 * Collapses (H x W x C) INT8 tensor to (C,) by averaging spatially.
 * Avoids floating-point by accumulating in int32 and dividing by H*W.
 *
 * @param input   INT8 tensor in HWC layout [H*W*C]
 * @param output  INT8 feature vector [C]
 * @param h, w, c Spatial and channel dimensions
 */
static void global_avg_pool_int8(
    const int8_t *input,
    int8_t       *output,
    uint16_t h, uint16_t w, uint16_t c)
{
    uint32_t hw = (uint32_t)h * w;

    for (uint16_t ch = 0; ch < c; ch++) {
        int32_t acc = 0;
        for (uint32_t spatial = 0; spatial < hw; spatial++) {
            acc += (int32_t)input[spatial * c + ch];
        }
        /* Divide with rounding */
        acc = (acc + (int32_t)(hw >> 1)) / (int32_t)hw;
        output[ch] = saturate_int8(acc);
    }
}

/* ── Model flatbuffer magic check ────────────────────────────────────── */
/* TFLite flatbuffer starts with identifier "TFL3" at offset 4 */
static const uint8_t TFLITE_MAGIC[4] = {'T', 'F', 'L', '3'};

static int is_valid_tflite(const uint8_t *data, size_t len) {
    if (len < 8) return 0;
    return (memcmp(data + 4, TFLITE_MAGIC, 4) == 0);
}

/* ── run_inference() ─────────────────────────────────────────────────── */

InferenceStatus run_inference(
    const int8_t  *input,
    size_t         input_len,
    const uint8_t *model_data,
    size_t         model_len,
    int8_t        *output_score)
{
    if (!input || !model_data || !output_score) return INFERENCE_ERR_NULL_PTR;
    if (!is_valid_tflite(model_data, model_len)) return INFERENCE_ERR_BAD_MODEL;
    if (input_len < (size_t)(64 * 64 * 3))       return INFERENCE_ERR_SIZE;

    /*
     * Architecture:
     *   Input (64×64×3 INT8)
     *   → [MobileNetV2 backbone runs pre-quantized, output is 64-dim vector]
     *   → Dense(64, ReLU)
     *   → Dense(1, Sigmoid)
     *
     * NOTE: The MobileNetV2 convolutional backbone cannot run on bare-metal
     *       without TFLite Micro. For full CNN inference, see README Section 4
     *       on integrating TFLite Micro.
     *
     *       This engine implements the DENSE HEAD only (post-GAP layers).
     *       The 64-dim feature vector must come from running the backbone
     *       offline and embedding the result in test_image.h — OR from
     *       TFLite Micro running the full model.
     *
     *       For the simulation demo, we use a downsampled mean of the input
     *       as a placeholder feature vector to demonstrate the pipeline.
     */

    /* ── Step 1: Compute 64-dim feature vector from input ────────────── */
    /* Simplified: take mean of each 64-pixel block across spatial dims  */
    uint16_t block = (64 * 64 * 3) / L1_IN;
    for (uint16_t f = 0; f < L1_IN; f++) {
        int32_t acc = 0;
        for (uint16_t k = 0; k < block; k++) {
            acc += (int32_t)input[(int32_t)f * block + k];
        }
        s_buf_a[f] = saturate_int8(acc / (int32_t)block);
    }

    /* ── Step 2: Dense Layer 1 — 64 → 64, ReLU ───────────────────────── */
    dense_layer_int8(
        s_buf_a, s_w1, s_b1, s_buf_b,
        L1_IN, L1_OUT,
        L1_MULTIPLIER, L1_SHIFT, L1_OUT_ZERO,
        ACT_RELU
    );

    /* ── Step 3: Dense Layer 2 — 64 → 1, Sigmoid ─────────────────────── */
    dense_layer_int8(
        s_buf_b, s_w2, s_b2, s_buf_a,
        L2_IN, L2_OUT,
        L2_MULTIPLIER, L2_SHIFT, L2_OUT_ZERO,
        ACT_SIGMOID
    );

    *output_score = s_buf_a[0];
    return INFERENCE_OK;
}
