/**
 * model_params.h — PLACEHOLDER
 * This file is auto-generated by the Python training notebook.
 * Run CrackDetection_Training.ipynb Step 8 & 9 to regenerate.
 *
 * For SIMULATION MODE (no board), the model_data array is not needed —
 * define SIMULATION_MODE and weights are loaded via weights/*.inc files.
 */
#ifndef MODEL_PARAMS_H
#define MODEL_PARAMS_H

#include <stdint.h>

/* Populated after running the notebook */
#define MODEL_DATA_LEN         1U    /* placeholder — replace after training */
#define IMG_SIZE               64
#define IMG_CHANNELS           3
#define NUM_CLASSES            2
#define CRACK_THRESHOLD_INT8   0

#define LABEL_NO_CRACK  0
#define LABEL_CRACK     1

extern const uint8_t g_model_data[MODEL_DATA_LEN];

#endif /* MODEL_PARAMS_H */
